### ISSUE TITLE
Harp Of Yoba -> Tree Magic

### ISSUE THREAD

**Issue by AustinYQM** [Platonymous/Stardew-Valley-Mods#15]
The Tree song has not functioned since the update to the toolkit.

The following error just repeats over and over in smapi. One tree shakes for a good minute and the magnetism buff never happens.

`[SMAPI] An error occured in the base update loop: System.NullReferenceException: Object reference not set to an instance of an object.
   at HarpOfYobaRedux.TreeMagic.doMagic(Boolean playedToday) in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\Magic\TreeMagic.cs:line 61
   at HarpOfYobaRedux.SheetMusic.doMagic() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\SheetMusic.cs:line 132
   at HarpOfYobaRedux.Instrument.doMagic() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\Instrument.cs:line 231
   at PyTK.PyUtils.<>c__DisplayClass8_0.<setDelayedAction>b__0() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\PyTK\PyUtils.cs:line 41
   at StardewValley.DelayedAction.update(GameTime time)
   at StardewValley.Game1.UpdateOther(GameTime time)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550`

**Comment by AustinYQM** [comment]
After the merge I suggested it now affects all trees in the area however the magnetism buff does not happen and the trees shake multiple times for a good while. A new error, about a dictionary, has appeared. I will try tho paste it here later today.

**Comment by AustinYQM** [comment]
```
[SMAPI] An error occured in the base update loop: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HarpOfYobaRedux.TreeMagic.doMagic(Boolean playedToday) in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\Magic\TreeMagic.cs:line 29
   at HarpOfYobaRedux.SheetMusic.doMagic() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\SheetMusic.cs:line 132
   at HarpOfYobaRedux.Instrument.doMagic() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\HarpOfYobaRedux\Instrument.cs:line 231
   at PyTK.PyUtils.<>c__DisplayClass8_0.<setDelayedAction>b__0() in C:\Users\David\Documents\GitHub\Stardew-Valley-Mods\PyTK\PyUtils.cs:line 41
   at StardewValley.DelayedAction.update(GameTime time)
   at StardewValley.Game1.UpdateOther(GameTime time)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 550
```

**Comment by Platonymous** [comment]
Fixed
