### ISSUE TITLE
PelicanTTS

### ISSUE THREAD

**Issue by Sheref14** [Platonymous/Stardew-Valley-Mods#153]
[PelicanTTS] Mod crashed on entry and might not work correctly. Technical details:
System.Exception: Parameter "text" not found in method static System.Void Pathoschild.Stardew.LookupAnything.DrawTextHelper::InitIfNeeded()
   at HarmonyLib.MethodPatcher.EmitCallParameter(MethodInfo patch, Dictionary`2 variables, LocalBuilder runOriginalVariable, Boolean allowFirsParamPassthrough, LocalBuilder& tmpObjectVar, List`1 tmpBoxVars)
   at HarmonyLib.MethodPatcher.<>c__DisplayClass36_0.<AddPrefixes>b__0(MethodInfo fix)
   at HarmonyLib.MethodPatcher.AddPrefixes(Dictionary`2 variables, LocalBuilder runOriginalVariable)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at PelicanTTS.Screengraber..ctor() in C:\Users\Chris\Documents\Git\Stardew-Valley-Mods\PelicanTTS\Screengraber.cs:line 52
   at PelicanTTS.PelicanTTSMod.Entry(IModHelper helper) in C:\Users\Chris\Documents\Git\Stardew-Valley-Mods\PelicanTTS\PelicanTTSMod.cs:line 67
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1766.

**Comment by Sheref14** [comment]
not compatible with Lookup Anything
