### ISSUE TITLE
CFR: Log Spam and prevents screen updating/sleeping/changing maps

### ISSUE THREAD

**Issue by Jellypowered** [Platonymous/Stardew-Valley-Mods#42]
Will update this with more details once I have some time this evening...

[03:26:13 ERROR game] An error occured in the base update loop: System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomFarmingRedux.CustomMachine.performToolAction(Tool t, GameLocation location) in D:\Programming\Games\Mods\GitHub\Stardew-Valley-Mods\CustomFarmingRedux\CustomMachine.cs:line 878
   at StardewValley.GameLocation.characterDestroyObjectWithinRectangle(Rectangle rect, Boolean showDestroyedObject) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:line 5865
   at StardewValley.Character.MovePosition(GameTime time, Rectangle viewport, GameLocation currentLocation) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Character.cs:line 524
   at StardewValley.NPC.MovePosition(GameTime time, Rectangle viewport, GameLocation currentLocation) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\NPC.cs:line 1445
   at StardewValley.PathFindController.moveCharacter(GameTime time) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\PathFindController.cs:line 370
   at StardewValley.PathFindController.update(GameTime time) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\PathFindController.cs:line 149
   at StardewValley.Character.update(GameTime time, GameLocation location, Int64 id, Boolean move) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Character.cs:line 1043
   at StardewValley.Character.update(GameTime time, GameLocation location) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Character.cs:line 975
   at StardewValley.NPC.update(GameTime time, GameLocation location) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\NPC.cs:line 1682
   at StardewValley.GameLocation.updateCharacters(GameTime time) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:line 2043
   at StardewValley.GameLocation.updateEvenIfFarmerIsntHere(GameTime time, Boolean ignoreWasUpdatedFlush) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Locations\GameLocation.cs:line 2069
   at StardewValley.Game1.UpdateLocations(GameTime time) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 3558
   at StardewValley.Game1._update(GameTime gameTime) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 2408
   at Update_Patch1(Object gameTime, GameTime )

80mb in log file... fixed by having second player log off/force close game 

Multiplayer - same mods, only custom machines i'm running is the "improved machines" by GalekG
Bug seems to only occur when player is upgrading cabin (will test if upgrading farm house causes this today) 

Hope this helps in some way. Let me know if you need more information 

Jelly 

Log file: https://log.smapi.io/A0ypaj4z

**Comment by Jellypowered** [comment]
Ok so more information: 

it's random. doesn't seem to have anything to do with robin and/or multiplayer. Playing single player on the same map with some custom machines causes it too. when the error happens, the screen stops scrolling, In single player I can get myself to the farm house by repeatedly opening the inventory screen which causes the screen to center around my character (letting me get to my house just slowly) and sleeping for the night fixes the problem temporarily. 

Happens if time is paused or not, so not thinking its a conflict with TimeSpeed (I don't use the pause feature of Joys of efficiency)
